version: '3'
services:
  my-backend:
    image: totorigoloto/back:latest
    ports:
      - "5000:5000"

  my-frontend:
    image: totorigoloto/front:latest
    ports:
      - "8080:80"
    environment:
      - WS_BACK_URL=http://my-backend:5000
    
